export const ADD_SERVICES = 'ADD_SERVICES';
export const SERVICES_LOADING = 'SERVICES_LOADING';
export const SERVICES_FAILED = 'SERVICES_FAILED';

export const ADD_CLIENTS = 'ADD_CLIENTS';
export const CLIENTS_LOADING = 'CLIENTS_LOADING';
export const CLIENTS_FAILED = 'CLIENTS_FAILED';